import storyCover from '@/assets/story-cover.jpg';
import storySection1 from '@/assets/story-section-1.jpg';
import storySection2 from '@/assets/story-section-2.jpg';
import storySection3 from '@/assets/story-section-3.jpg';
import storySection4 from '@/assets/story-section-4.jpg';
import storySection5 from '@/assets/story-section-5.jpg';
import story2Cover from '@/assets/story-2-cover.jpg';
import story3Cover from '@/assets/story-3-cover.jpg';
import masterArtwork from '@/assets/master-artwork.jpg';
import atlasCathedral from '@/assets/atlas-cathedral.jpg';
import atlasMarket from '@/assets/atlas-market.jpg';
import atlasHarbor from '@/assets/atlas-harbor.jpg';
import atlasCourt from '@/assets/atlas-court.jpg';
import atlasRuins from '@/assets/atlas-ruins.jpg';
import atlasPanorama from '@/assets/atlas-panorama.jpg';
import desertRuins from '@/assets/story-desert-ruins.jpg';
import cartographer from '@/assets/story-cartographer.jpg';
import cathedralLight from '@/assets/story-cathedral-light.jpg';
import type { Story } from './types';

export const demoStories: Story[] = [
  // ── FLAGSHIP LONG-FORM STORY: The Atlas of a Forgotten City ──
  {
    id: '5',
    slug: 'atlas-of-a-forgotten-city',
    title: 'The Atlas of a Forgotten City',
    subtitle: 'Six paintings. One lost civilization. A cinematic journey across faith, commerce, power, ruin, and memory.',
    coverImage: atlasPanorama,
    author: 'Chronicle Editorial',
    date: 'April 2026',
    readTime: '18 min read',
    featured: true,
    status: 'published',
    images: [atlasPanorama, atlasCathedral, atlasMarket, atlasHarbor, atlasCourt, atlasRuins],
    states: [
      // ── ACT I: THE PANORAMA (image 0) — 8 states ──
      { id: 'a1',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [] },
      { id: 'a2',  imageIndex: 0, zoom: { scale: 1.8, x: -30, y: -12 }, overlays: [], easing: 'ease-in-out' },
      { id: 'a3',  imageIndex: 0, zoom: { scale: 3.0, x: -40, y: 15  }, overlays: [], easing: 'ease-in-out' },
      { id: 'a4',  imageIndex: 0, zoom: { scale: 4.5, x: -15, y: 25  }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.35, y: 0.65, width: 0.12, height: 0.12, opacity: 0.4 }], easing: 'ease-out' },
      { id: 'a5',  imageIndex: 0, zoom: { scale: 2.0, x: 30,  y: 5   }, overlays: [], easing: 'ease-in-out' },
      { id: 'a6',  imageIndex: 0, zoom: { scale: 4.8, x: 35,  y: -15 }, overlays: [{ type: 'highlight', shape: 'rect', x: 0.6, y: 0.3, width: 0.2, height: 0.15, opacity: 0.3 }], easing: 'ease-out' },
      { id: 'a7',  imageIndex: 0, zoom: { scale: 1.4, x: 0,   y: -30 }, overlays: [], easing: 'ease-in-out' },
      { id: 'a8',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },

      // ── ACT II: THE CATHEDRAL (image 1) — 8 states ──
      { id: 'b1',  imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'b2',  imageIndex: 1, zoom: { scale: 2.0, x: 0,   y: -35 }, overlays: [], easing: 'ease-in-out' },
      { id: 'b3',  imageIndex: 1, zoom: { scale: 4.0, x: -10, y: -45 }, overlays: [{ type: 'highlight', shape: 'rect', x: 0.3, y: 0.05, width: 0.4, height: 0.2, opacity: 0.25, color: 'hsl(45, 80%, 60%)' }], easing: 'ease-out' },
      { id: 'b4',  imageIndex: 1, zoom: { scale: 2.5, x: -35, y: -10 }, overlays: [], easing: 'ease-in-out' },
      { id: 'b5',  imageIndex: 1, zoom: { scale: 3.5, x: 30,  y: -20 }, overlays: [], easing: 'ease-in-out' },
      { id: 'b6',  imageIndex: 1, zoom: { scale: 5.0, x: 0,   y: 10  }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.5, y: 0.55, width: 0.15, height: 0.15, opacity: 0.35 }], easing: 'ease-out' },
      { id: 'b7',  imageIndex: 1, zoom: { scale: 2.5, x: 10,  y: 30  }, overlays: [], easing: 'ease-in-out' },
      { id: 'b8',  imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },

      // ── ACT III: THE MARKET (image 2) — 8 states ──
      { id: 'c1',  imageIndex: 2, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'c2',  imageIndex: 2, zoom: { scale: 2.5, x: -35, y: 10  }, overlays: [], easing: 'ease-in-out' },
      { id: 'c3',  imageIndex: 2, zoom: { scale: 4.5, x: -45, y: 20  }, overlays: [{ type: 'highlight', shape: 'rect', x: 0.05, y: 0.4, width: 0.25, height: 0.3, opacity: 0.3 }], easing: 'ease-out' },
      { id: 'c4',  imageIndex: 2, zoom: { scale: 2.0, x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'c5',  imageIndex: 2, zoom: { scale: 3.8, x: 30,  y: -10 }, overlays: [], easing: 'ease-in-out' },
      { id: 'c6',  imageIndex: 2, zoom: { scale: 5.2, x: 40,  y: 15  }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.8, y: 0.6, width: 0.1, height: 0.1, opacity: 0.4 }], easing: 'ease-out' },
      { id: 'c7',  imageIndex: 2, zoom: { scale: 1.5, x: 10,  y: -25 }, overlays: [], easing: 'ease-in-out' },
      { id: 'c8',  imageIndex: 2, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },

      // ── ACT IV: THE HARBOR (image 3) — 7 states ──
      { id: 'd1',  imageIndex: 3, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'd2',  imageIndex: 3, zoom: { scale: 2.2, x: 0,   y: -30 }, overlays: [], easing: 'ease-in-out' },
      { id: 'd3',  imageIndex: 3, zoom: { scale: 4.0, x: -35, y: 10  }, overlays: [], easing: 'ease-in-out' },
      { id: 'd4',  imageIndex: 3, zoom: { scale: 4.8, x: 0,   y: 0   }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.5, y: 0.4, width: 0.18, height: 0.18, opacity: 0.25 }], easing: 'ease-out' },
      { id: 'd5',  imageIndex: 3, zoom: { scale: 3.0, x: 35,  y: 15  }, overlays: [], easing: 'ease-in-out' },
      { id: 'd6',  imageIndex: 3, zoom: { scale: 4.5, x: 40,  y: -15 }, overlays: [], easing: 'ease-out' },
      { id: 'd7',  imageIndex: 3, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },

      // ── ACT V: THE COURT (image 4) — 8 states ──
      { id: 'e1',  imageIndex: 4, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'e2',  imageIndex: 4, zoom: { scale: 2.2, x: 0,   y: 12  }, overlays: [], easing: 'ease-in-out' },
      { id: 'e3',  imageIndex: 4, zoom: { scale: 4.5, x: 0,   y: -10 }, overlays: [{ type: 'highlight', shape: 'rect', x: 0.35, y: 0.2, width: 0.3, height: 0.4, opacity: 0.25 }], easing: 'ease-out' },
      { id: 'e4',  imageIndex: 4, zoom: { scale: 5.0, x: 0,   y: -30 }, overlays: [], easing: 'ease-in-out' },
      { id: 'e5',  imageIndex: 4, zoom: { scale: 3.5, x: -40, y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'e6',  imageIndex: 4, zoom: { scale: 3.5, x: 40,  y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'e7',  imageIndex: 4, zoom: { scale: 5.5, x: 0,   y: 25  }, overlays: [{ type: 'highlight', shape: 'rect', x: 0.25, y: 0.7, width: 0.5, height: 0.2, opacity: 0.25, color: 'hsl(30, 50%, 50%)' }], easing: 'ease-out' },
      { id: 'e8',  imageIndex: 4, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },

      // ── ACT VI: THE RUINS (image 5) — 7 states ──
      { id: 'f1',  imageIndex: 5, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'f2',  imageIndex: 5, zoom: { scale: 2.5, x: -30, y: -10 }, overlays: [], easing: 'ease-in-out' },
      { id: 'f3',  imageIndex: 5, zoom: { scale: 4.5, x: -40, y: 20  }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.2, y: 0.75, width: 0.15, height: 0.15, opacity: 0.35 }], easing: 'ease-out' },
      { id: 'f4',  imageIndex: 5, zoom: { scale: 3.5, x: 0,   y: 0   }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.5, y: 0.5, width: 0.08, height: 0.12, opacity: 0.4 }], easing: 'ease-in-out' },
      { id: 'f5',  imageIndex: 5, zoom: { scale: 4.0, x: 35,  y: -20 }, overlays: [], easing: 'ease-in-out' },
      { id: 'f6',  imageIndex: 5, zoom: { scale: 1.5, x: 0,   y: -35 }, overlays: [], easing: 'ease-in-out' },
      { id: 'f7',  imageIndex: 5, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
    ],
    paragraphs: [
      // ACT I: PANORAMA (8)
      { id: 'ap1',  stateId: 'a1', text: 'From a distance, the city appears whole. Terracotta rooftops stretch to the sea, domes rise above the haze, and church bells mark an hour that no longer exists.', caption: 'The City at Dawn' },
      { id: 'ap2',  stateId: 'a2', text: 'To the west, the oldest quarter clings to the hillside. These buildings were raised before the city had a name.' },
      { id: 'ap3',  stateId: 'a3', text: 'Down near the waterfront, a cluster of low stone houses. Fishermen lived here once. Their nets dried on these rooftops.' },
      { id: 'ap4',  stateId: 'a4', text: 'This dome belongs to the Church of San Matteo. It was the heart of the city — the place where treaties were signed and orphans were sheltered.' },
      { id: 'ap5',  stateId: 'a5', text: 'Across the rooftops to the east, the merchant district begins. Taller buildings, narrower streets, the geometry of profit.' },
      { id: 'ap6',  stateId: 'a6', text: 'Here, a bell tower stands above the rest. It was the last structure completed before the city fell. The bell was never rung.', caption: 'The Silent Bell Tower' },
      { id: 'ap7',  stateId: 'a7', text: 'Above it all, the sky holds the morning mist. Birds circle in patterns that have not changed in centuries.' },
      { id: 'ap8',  stateId: 'a8', text: 'This is the city as it was. Now we go inside.' },

      // ACT II: CATHEDRAL (8)
      { id: 'bp1',  stateId: 'b1', text: 'The cathedral was the largest building in the city. Its nave could hold a thousand worshippers. Today, only light enters.', caption: 'Interior of the Grand Cathedral' },
      { id: 'bp2',  stateId: 'b2', text: 'Look up. The ceiling frescoes depict the founding myths — gods descending, rivers parting, the first stone being laid.' },
      { id: 'bp3',  stateId: 'b3', text: 'These frescoes took three generations of painters to complete. The final brushstroke was applied in 1487.' },
      { id: 'bp4',  stateId: 'b4', text: 'Along the left wall, light pours through stained glass. The beams cut the darkness like blades, landing on marble columns that have stood for five hundred years.' },
      { id: 'bp5',  stateId: 'b5', text: 'On the right, deeper shadow. Statues of saints stand in niches, watching the empty nave with stone eyes.' },
      { id: 'bp6',  stateId: 'b6', text: 'In the center, among the gathered crowd, two figures in white stand apart. A ceremony is taking place — or ending.', caption: 'The Ceremony' },
      { id: 'bp7',  stateId: 'b7', text: 'At the far end, the altar gleams. Gold leaf and candlelight. The sacred and the theatrical are inseparable here.' },
      { id: 'bp8',  stateId: 'b8', text: 'We leave the cathedral and step outside, into the noise and color of the streets.' },

      // ACT III: MARKET (8)
      { id: 'cp1',  stateId: 'c1', text: 'The marketplace was the lungs of the city. Every morning, it breathed in goods from three continents and exhaled gossip, debt, and ambition.', caption: 'The Grand Bazaar at Golden Hour' },
      { id: 'cp2',  stateId: 'c2', text: 'On the left, the silk and spice merchants. Their stalls are draped in color — saffron yellow, indigo, the deep red of paprika brought overland from the East.' },
      { id: 'cp3',  stateId: 'c3', text: 'This merchant, seated low, arranges his wares with care. Each basket tells a story of a trade route, a ship, a season.' },
      { id: 'cp4',  stateId: 'c4', text: 'Through the center, the crowd moves in both directions. Buyers and sellers, pickpockets and priests, all sharing the same stone path.' },
      { id: 'cp5',  stateId: 'c5', text: 'To the right, beneath the arch, a passage leads to the foreign quarter. Traders from distant lands conducted business in languages the city never fully learned.' },
      { id: 'cp6',  stateId: 'c6', text: 'In the far corner, a group huddles in conversation. Not commerce — conspiracy, perhaps, or simply friendship. The painting does not tell us.', caption: 'Conversations at the Edge' },
      { id: 'cp7',  stateId: 'c7', text: 'Above the stalls, the sky turns amber. The market will close soon. The last negotiations are always the most desperate.' },
      { id: 'cp8',  stateId: 'c8', text: 'We leave the market through the eastern gate, toward the water.' },

      // ACT IV: HARBOR (7)
      { id: 'dp1',  stateId: 'd1', text: 'The harbor was the city\'s open hand — reaching outward, welcoming and releasing ships that carried its fortunes across the sea.', caption: 'The Harbor at Sunset' },
      { id: 'dp2',  stateId: 'd2', text: 'The sky above burns gold and copper. The sun sits on the horizon, its reflection splitting the water into two halves — one bright, one dark.' },
      { id: 'dp3',  stateId: 'd3', text: 'To the left, the fortress walls. Built to protect the harbor from enemies who arrived by sea. The stonework is scarred from at least two sieges.' },
      { id: 'dp4',  stateId: 'd4', text: 'In the center, the merchant vessel. Its sails hang half-furled. It has just arrived, or is about to leave. The painting captures both possibilities at once.' },
      { id: 'dp5',  stateId: 'd5', text: 'On the right, fishermen pull in their nets. Their work is older than the city itself. It will outlast it, too.' },
      { id: 'dp6',  stateId: 'd6', text: 'Behind them, the fortress towers stand guard. Mountains rise in the distance — the natural boundary that once made this city feel invincible.', caption: 'The Fortress and the Mountain' },
      { id: 'dp7',  stateId: 'd7', text: 'The harbor fades behind us. We turn inland, toward the seat of power.' },

      // ACT V: COURT (8)
      { id: 'ep1',  stateId: 'e1', text: 'The throne room. This is where the city\'s fate was decided — not in battle, but in whispered agreements and ceremonial gestures.', caption: 'The Royal Court' },
      { id: 'ep2',  stateId: 'e2', text: 'The marble floor draws the eye inward. Its geometric pattern is a map of the cosmos — or so the court astrologer claimed.' },
      { id: 'ep3',  stateId: 'e3', text: 'At the center, the king sits on his throne. His posture is composed, his expression unreadable. The crown weighs more than it appears.' },
      { id: 'ep4',  stateId: 'e4', text: 'Behind him, a tapestry depicting the founding of the city. It was woven to remind the court of its origins — and its obligations.' },
      { id: 'ep5',  stateId: 'e5', text: 'To the left, the nobles of the old families. Their black garments signify authority. Their proximity to the throne is carefully measured.' },
      { id: 'ep6',  stateId: 'e6', text: 'To the right, the newer aristocracy. Their robes are lighter, more ornate. Wealth earned, not inherited. The king keeps both factions close.', caption: 'The Balance of Power' },
      { id: 'ep7',  stateId: 'e7', text: 'At their feet, the floor pattern converges. Star and compass rose intertwined. The court believed geometry could reveal divine will.' },
      { id: 'ep8',  stateId: 'e8', text: 'The audience ends. The courtiers disperse. The city has only a few decades left.' },

      // ACT VI: RUINS (7)
      { id: 'fp1',  stateId: 'f1', text: 'And then — this. The arches that once held ceilings now hold only sky. The columns that supported marble halls support climbing vines.', caption: 'What Remains' },
      { id: 'fp2',  stateId: 'f2', text: 'On the left, the grand arch. You can still see the mason\'s marks in the stone. Each block was cut by a named man, whose name is now lost.' },
      { id: 'fp3',  stateId: 'f3', text: 'At the base, wildflowers have taken root. Poppies, cornflowers, daisies. Color returns to the ruins in a language the city never spoke.' },
      { id: 'fp4',  stateId: 'f4', text: 'In the center, a solitary figure stands among the rubble. A traveler, a scholar, or simply someone who wandered in. They are looking at something we cannot see.', caption: 'The Last Witness' },
      { id: 'fp5',  stateId: 'f5', text: 'To the right, the columns lean. Gravity is patient. It has been pulling these stones earthward for centuries, and it will finish the work eventually.' },
      { id: 'fp6',  stateId: 'f6', text: 'Above it all, the sky opens wide. Golden clouds drift across a blue that has not changed since the city was built. The sky does not remember.' },
      { id: 'fp7',  stateId: 'f7', text: 'We step back. The ruins become a painting again. The city becomes a story. And the story, like all stories, ends where it began — with someone looking.', caption: 'The Atlas Closes' },
    ],
  },

  // ── Original stories below ──
  {
    id: '1',
    slug: 'the-last-ancient-forest',
    title: 'The Last Ancient Forest',
    subtitle: 'A journey into the world\'s oldest living ecosystem — and the race to save it',
    coverImage: storyCover,
    author: 'Elena Vasquez',
    date: 'March 2026',
    readTime: '12 min read',
    featured: false,
    status: 'published',
    images: [storyCover, storySection1, storySection2, storySection3, storySection4, storySection5],
    states: [
      { id: 'st1', imageIndex: 0, zoom: { scale: 1, x: 0, y: 0 }, overlays: [] },
      { id: 'st2', imageIndex: 0, zoom: { scale: 1.4, x: 10, y: 5 }, overlays: [], easing: 'ease-in-out' },
      { id: 'st3', imageIndex: 1, zoom: { scale: 1, x: 0, y: 0 }, overlays: [], easing: 'ease-in-out' },
      { id: 'st4', imageIndex: 1, zoom: { scale: 1.6, x: -8, y: 10 }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.5, y: 0.5, width: 0.3, height: 0.3, opacity: 0.6 }], easing: 'ease-out' },
      { id: 'st5', imageIndex: 2, zoom: { scale: 1.1, x: 0, y: 0 }, overlays: [], easing: 'ease-in-out' },
      { id: 'st6', imageIndex: 2, zoom: { scale: 1.8, x: 12, y: -5 }, overlays: [], easing: 'ease-in-out' },
      { id: 'st7', imageIndex: 3, zoom: { scale: 1, x: 0, y: 0 }, overlays: [], easing: 'ease-in-out' },
      { id: 'st8', imageIndex: 4, zoom: { scale: 1.2, x: -5, y: 8 }, overlays: [], easing: 'ease-in-out' },
      { id: 'st9', imageIndex: 4, zoom: { scale: 1.5, x: 8, y: -3 }, overlays: [{ type: 'highlight', shape: 'rect', x: 0.2, y: 0.3, width: 0.6, height: 0.4, opacity: 0.4 }], easing: 'ease-out' },
      { id: 'st10', imageIndex: 5, zoom: { scale: 1, x: 0, y: 0 }, overlays: [], easing: 'ease-in-out' },
      { id: 'st11', imageIndex: 5, zoom: { scale: 1.3, x: 0, y: -8 }, overlays: [], easing: 'ease-in-out' },
    ],
    paragraphs: [
      { id: 'p1', stateId: 'st1', text: 'Deep in the Pacific Northwest, a cathedral of ancient trees stands as it has for millennia — silent witnesses to the passage of time.', caption: 'Pacific Northwest, United States' },
      { id: 'p2', stateId: 'st2', text: 'Look closely at the bark. Each fissure is a chapter, each ring a century. These giants predate the modern world by thousands of years.' },
      { id: 'p3', stateId: 'st3', text: 'The forest floor exists in perpetual twilight. Ferns unfurl in filtered light, their fronds reaching upward like green flames. The air is thick with moisture and the scent of ancient decomposition.', caption: 'Less than 2% of sunlight reaches the forest floor' },
      { id: 'p4', stateId: 'st4', text: 'At the heart of each tree, a complex network of mycorrhizal fungi connects root to root — a wood-wide web through which nutrients and chemical signals flow between organisms.' },
      { id: 'p5', stateId: 'st5', text: 'Beneath the towering canopy, a world of moss and lichen colonizes every surface. These micro-ecosystems support hundreds of species that exist nowhere else on Earth.', caption: 'The understory canopy' },
      { id: 'p6', stateId: 'st6', text: 'Scientists have discovered that the oldest trees act as "mother trees," nurturing younger saplings through underground fungal networks — sharing sugars, water, and even warning signals about insect attacks.' },
      { id: 'p7', stateId: 'st7', text: 'From above, the rivers trace silver threads through an ocean of autumn color. These waterways are the forest\'s arteries, carrying nutrients from mountain peaks to valley floors.', caption: 'Aerial view, autumn' },
      { id: 'p8', stateId: 'st8', text: 'Standing at the boundary between wilderness and sky, one can see both the enormity of what remains and the fragility of its existence. Conservation efforts have accelerated, but the clock is ticking.' },
      { id: 'p9', stateId: 'st9', text: 'What we choose to protect today will define the world our children inherit. Every acre preserved is a library of genetic information, a carbon vault, a water purifier.' },
      { id: 'p10', stateId: 'st10', text: 'As night falls over the forest, the same stars that guided the first trees skyward continue their silent vigil. In the darkness, the forest breathes.', caption: 'Milky Way above old-growth forest' },
      { id: 'p11', stateId: 'st11', text: 'These ancient forests are more than landscapes. They are living archives, breathing cathedrals, and perhaps our best hope for understanding what it means to endure.' },
    ],
  },
  {
    id: '4',
    slug: 'the-painting-reveals-itself',
    title: 'The Painting Reveals Itself',
    subtitle: 'A cinematic journey into a Baroque masterwork — guided by scroll, revealed by light',
    coverImage: masterArtwork,
    author: 'Chronicle Editorial',
    date: 'April 2026',
    readTime: '8 min read',
    featured: false,
    status: 'published',
    images: [masterArtwork],
    states: [
      { id: 'cs1',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [] },
      { id: 'cs2',  imageIndex: 0, zoom: { scale: 1.2, x: 5,   y: -5  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs3',  imageIndex: 0, zoom: { scale: 1.5, x: 8,   y: -8  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs4',  imageIndex: 0, zoom: { scale: 1.8, x: 2,   y: -2  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs5',  imageIndex: 0, zoom: { scale: 2.4, x: 0,   y: -5  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs6',  imageIndex: 0, zoom: { scale: 3.2, x: -1,  y: -10 }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs7',  imageIndex: 0, zoom: { scale: 3.0, x: -4,  y: 3   }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs8',  imageIndex: 0, zoom: { scale: 2.5, x: -12, y: 2   }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs9',  imageIndex: 0, zoom: { scale: 3.0, x: -18, y: -3  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs10', imageIndex: 0, zoom: { scale: 2.8, x: -25, y: -5  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs11', imageIndex: 0, zoom: { scale: 2.5, x: 15,  y: -3  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs12', imageIndex: 0, zoom: { scale: 3.0, x: 20,  y: 10  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs13', imageIndex: 0, zoom: { scale: 2.8, x: 0,   y: -2  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs14', imageIndex: 0, zoom: { scale: 4.0, x: -1,  y: -12 }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs15', imageIndex: 0, zoom: { scale: 4.5, x: 1,   y: -14 }, overlays: [{ type: 'highlight', shape: 'circle', x: 0.48, y: 0.33, width: 0.08, height: 0.08, opacity: 0.35 }], easing: 'ease-in-out' },
      { id: 'cs16', imageIndex: 0, zoom: { scale: 4.2, x: 0,   y: -13 }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs17', imageIndex: 0, zoom: { scale: 2.5, x: 0,   y: -3  }, overlays: [], easing: 'ease-in-out' },
      { id: 'cs18', imageIndex: 0, zoom: { scale: 1.0, x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
    ],
    paragraphs: [
      { id: 'cp1',  stateId: 'cs1',  text: 'We see the entire scene. A group of figures, arranged around a single source of light.' },
      { id: 'cp2',  stateId: 'cs2',  text: 'The light enters from the upper right. It cuts through the darkness like a blade.' },
      { id: 'cp3',  stateId: 'cs3',  text: 'Follow it downward. The beam is deliberate. The painter placed it here for a reason.' },
      { id: 'cp4',  stateId: 'cs4',  text: 'It falls on the central figure. He is the only one fully illuminated.' },
      { id: 'cp5',  stateId: 'cs5',  text: 'His body is turned toward us. Draped in white cloth, exposed to the light. Every figure around him reacts to his presence.' },
      { id: 'cp6',  stateId: 'cs6',  text: 'His face. Half in light, half in shadow. This is the dividing line of the entire painting.' },
      { id: 'cp7',  stateId: 'cs7',  text: 'Now look at his hand. It reaches outward, palm open. The gesture is not aggressive — it is an offering.' },
      { id: 'cp8',  stateId: 'cs8',  text: 'Follow where the hand points. To the left, a figure in red leans forward.' },
      { id: 'cp9',  stateId: 'cs9',  text: 'The red-robed figure. His posture suggests urgency. He is responding to something he has just witnessed.' },
      { id: 'cp10', stateId: 'cs10', text: 'Behind him, at the far edge, others watch. Their faces are barely visible. They are witnesses, not participants.' },
      { id: 'cp11', stateId: 'cs11', text: 'On the opposite side, another group. Their bodies angle inward, drawn toward the center.' },
      { id: 'cp12', stateId: 'cs12', text: 'At the bottom right, a figure is collapsed. Overcome. The drama has already reached him.' },
      { id: 'cp13', stateId: 'cs13', text: 'Return to the center. Everything in this painting radiates from this single figure.' },
      { id: 'cp14', stateId: 'cs14', text: 'His face again. Closer now. The expression is calm despite the surrounding tension.' },
      { id: 'cp15', stateId: 'cs15', text: 'Here, at the exact boundary where light meets shadow, the painter has placed the entire meaning of the work.' },
      { id: 'cp16', stateId: 'cs16', text: 'This is the moment the painting holds. Frozen. Permanent. A single breath caught in oil and pigment.' },
      { id: 'cp17', stateId: 'cs17', text: 'We begin to step back. The individual figures recede into the composition.' },
      { id: 'cp18', stateId: 'cs18', text: 'And once again, we see the whole. But now we understand what lives inside it.' },
    ],
  },
  // ── STORY: The Silent Language of Light ──
  {
    id: '6',
    slug: 'silent-language-of-light',
    title: 'The Silent Language of Light',
    subtitle: 'Inside a cathedral where every beam tells a story written eight centuries ago',
    coverImage: cathedralLight,
    author: 'Elena Vasquez',
    date: 'March 2026',
    readTime: '12 min read',
    status: 'published',
    images: [cathedralLight, atlasCathedral],
    states: [
      { id: 'sl1',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [] },
      { id: 'sl2',  imageIndex: 0, zoom: { scale: 2.2, x: 0,   y: -25 }, overlays: [], easing: 'ease-in-out' },
      { id: 'sl3',  imageIndex: 0, zoom: { scale: 4.0, x: -15, y: -35 }, overlays: [], easing: 'ease-out' },
      { id: 'sl4',  imageIndex: 0, zoom: { scale: 3.2, x: 25,  y: -20 }, overlays: [], easing: 'ease-in-out' },
      { id: 'sl5',  imageIndex: 0, zoom: { scale: 5.0, x: 10,  y: 10  }, overlays: [], easing: 'ease-out' },
      { id: 'sl6',  imageIndex: 0, zoom: { scale: 2.0, x: -30, y: 15  }, overlays: [], easing: 'ease-in-out' },
      { id: 'sl7',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
      { id: 'sl8',  imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'sl9',  imageIndex: 1, zoom: { scale: 2.5, x: -20, y: -30 }, overlays: [], easing: 'ease-in-out' },
      { id: 'sl10', imageIndex: 1, zoom: { scale: 4.5, x: 0,   y: -40 }, overlays: [], easing: 'ease-out' },
      { id: 'sl11', imageIndex: 1, zoom: { scale: 3.0, x: 30,  y: 10  }, overlays: [], easing: 'ease-in-out' },
      { id: 'sl12', imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
    ],
    paragraphs: [
      { id: 'slp1',  stateId: 'sl1',  text: 'You step inside and the world falls silent. The noise of the street, the wind, the traffic — all of it stays at the threshold.' },
      { id: 'slp2',  stateId: 'sl2',  text: 'Your eyes are drawn upward. The vaulted ceiling soars above, ribs of stone converging at a point so high it seems to dissolve into shadow.' },
      { id: 'slp3',  stateId: 'sl3',  text: 'And then — light. Not the pale wash of a bulb, but something vivid. Colored. Alive. It pours through the rose window like liquid fire.' },
      { id: 'slp4',  stateId: 'sl4',  text: 'The glass was placed here with mathematical precision. At this hour, on this day, the beams reach the floor tiles exactly where the builders intended.' },
      { id: 'slp5',  stateId: 'sl5',  text: 'Look closer. Each panel tells a chapter. Saints and sinners, kings and shepherds. Eight centuries of pigment fused into glass by hands long turned to dust.' },
      { id: 'slp6',  stateId: 'sl6',  text: 'The light shifts. A cloud passes outside and the interior breathes — colors dimming, then returning brighter than before.' },
      { id: 'slp7',  stateId: 'sl7',  text: 'Step back. See the full nave. This is architecture as argument: that the divine is not somewhere else, but here, in the geometry of stone and light.' },
      { id: 'slp8',  stateId: 'sl8',  text: 'A second cathedral, a thousand miles away. Built in the same century, by builders who never met, following the same invisible logic.' },
      { id: 'slp9',  stateId: 'sl9',  text: 'The columns here are thicker, the arches more muscular. This is not grace but strength. A fortress that prays.' },
      { id: 'slp10', stateId: 'sl10', text: 'At the apex, a single oculus. The builders left this opening as a lens. Through it, the sun writes the hour on the floor.' },
      { id: 'slp11', stateId: 'sl11', text: 'In the side chapel, candles burn before carved figures. The wax has pooled into shapes that mirror the stonework above.' },
      { id: 'slp12', stateId: 'sl12', text: 'You leave the way you entered. But the silence follows you now. It has attached itself to something inside you, and it will not let go.' },
    ],
  },

  // ── STORY: Fragments of Empire ──
  {
    id: '7',
    slug: 'fragments-of-empire',
    title: 'Fragments of Empire',
    subtitle: 'An archaeological dig uncovers the last temple of a civilization that vanished overnight',
    coverImage: desertRuins,
    author: 'Khalid Nasser',
    date: 'March 2026',
    readTime: '14 min read',
    status: 'published',
    images: [desertRuins, atlasRuins, atlasPanorama],
    states: [
      { id: 'fe1',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [] },
      { id: 'fe2',  imageIndex: 0, zoom: { scale: 1.6, x: 0,   y: 15  }, overlays: [], easing: 'ease-in-out' },
      { id: 'fe3',  imageIndex: 0, zoom: { scale: 3.5, x: -10, y: 20  }, overlays: [], easing: 'ease-out' },
      { id: 'fe4',  imageIndex: 0, zoom: { scale: 4.8, x: 15,  y: 10  }, overlays: [], easing: 'ease-out' },
      { id: 'fe5',  imageIndex: 0, zoom: { scale: 2.0, x: 30,  y: -15 }, overlays: [], easing: 'ease-in-out' },
      { id: 'fe6',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
      { id: 'fe7',  imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'fe8',  imageIndex: 1, zoom: { scale: 2.8, x: -25, y: -10 }, overlays: [], easing: 'ease-in-out' },
      { id: 'fe9',  imageIndex: 1, zoom: { scale: 5.0, x: -35, y: 20  }, overlays: [], easing: 'ease-out' },
      { id: 'fe10', imageIndex: 1, zoom: { scale: 3.0, x: 20,  y: -25 }, overlays: [], easing: 'ease-in-out' },
      { id: 'fe11', imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
      { id: 'fe12', imageIndex: 2, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'fe13', imageIndex: 2, zoom: { scale: 2.5, x: 15,  y: 10  }, overlays: [], easing: 'ease-in-out' },
      { id: 'fe14', imageIndex: 2, zoom: { scale: 4.0, x: -20, y: -15 }, overlays: [], easing: 'ease-out' },
      { id: 'fe15', imageIndex: 2, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
    ],
    paragraphs: [
      { id: 'fep1',  stateId: 'fe1',  text: 'From the air it looks like nothing. A smudge of geometry in an ocean of sand. But geometry does not occur naturally in deserts.' },
      { id: 'fep2',  stateId: 'fe2',  text: 'We descend. The shadows sharpen. What seemed like erosion reveals itself as intention — walls, doorways, the skeleton of a building that once held a roof.' },
      { id: 'fep3',  stateId: 'fe3',  text: 'The temple entrance faces east. Not by accident. The builders aligned it to catch the first light of the equinox, a door that opened once a year to the sun.' },
      { id: 'fep4',  stateId: 'fe4',  text: 'Carvings in the lintel stone. Worn by wind but still legible: figures carrying vessels, a procession frozen in sandstone for three thousand years.' },
      { id: 'fep5',  stateId: 'fe5',  text: 'Beyond the temple, the dunes have swallowed everything. Streets, houses, granaries — all buried under meters of amber sand.' },
      { id: 'fep6',  stateId: 'fe6',  text: 'We pull back. From here the temple is a footnote. The desert has reclaimed its territory and the temple exists now only as a rumor on the surface.' },
      { id: 'fep7',  stateId: 'fe7',  text: 'Fifty kilometers south, a second site. This one was found by satellite — thermal imaging revealed walls that the eye could never see.' },
      { id: 'fep8',  stateId: 'fe8',  text: 'The excavation has been meticulous. Brush by brush, they have peeled back centuries. What emerged was not a temple but a palace.' },
      { id: 'fep9',  stateId: 'fe9',  text: 'In the inner chamber, pottery shards. Hundreds of them. Each one painted with a pigment derived from crushed lapis lazuli — a material that had to travel two thousand miles to reach this room.' },
      { id: 'fep10', stateId: 'fe10', text: 'The question that haunts every archaeologist here: what happened? No signs of war. No evidence of famine. The city was simply abandoned, as if its people walked away in a single afternoon.' },
      { id: 'fep11', stateId: 'fe11', text: 'We step back from the dig site. The tools are covered for the night. Tomorrow they will continue, one centimeter at a time.' },
      { id: 'fep12', stateId: 'fe12', text: 'From the ridge, you can see both sites. Two points of stone in a landscape that has erased everything between them.' },
      { id: 'fep13', stateId: 'fe13', text: 'The team\'s geologist believes there was a river here once. A wide, slow river that fed the fields and filled the cisterns. When it shifted course, the empire lost its spine.' },
      { id: 'fep14', stateId: 'fe14', text: 'In the dust, a child\'s toy. A clay animal, roughly shaped, with one leg missing. Someone made this for someone they loved. That is the only certainty we have.' },
      { id: 'fep15', stateId: 'fe15', text: 'The wind picks up. Sand begins to reclaim the day\'s work. In a thousand years, this too will be a layer waiting to be found.' },
    ],
  },

  // ── STORY: The Last Cartographers ──
  {
    id: '8',
    slug: 'the-last-cartographers',
    title: 'The Last Cartographers',
    subtitle: 'In an age of satellites, a handful of people still draw the world by hand',
    coverImage: cartographer,
    author: 'James Whitfield',
    date: 'February 2026',
    readTime: '10 min read',
    status: 'published',
    images: [cartographer, masterArtwork],
    states: [
      { id: 'lc1',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [] },
      { id: 'lc2',  imageIndex: 0, zoom: { scale: 2.0, x: 0,   y: 5   }, overlays: [], easing: 'ease-in-out' },
      { id: 'lc3',  imageIndex: 0, zoom: { scale: 4.0, x: -5,  y: 0   }, overlays: [], easing: 'ease-out' },
      { id: 'lc4',  imageIndex: 0, zoom: { scale: 3.5, x: 20,  y: -10 }, overlays: [], easing: 'ease-in-out' },
      { id: 'lc5',  imageIndex: 0, zoom: { scale: 5.0, x: -25, y: 15  }, overlays: [], easing: 'ease-out' },
      { id: 'lc6',  imageIndex: 0, zoom: { scale: 2.5, x: 15,  y: 20  }, overlays: [], easing: 'ease-in-out' },
      { id: 'lc7',  imageIndex: 0, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
      { id: 'lc8',  imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-in-out' },
      { id: 'lc9',  imageIndex: 1, zoom: { scale: 2.5, x: -30, y: -15 }, overlays: [], easing: 'ease-in-out' },
      { id: 'lc10', imageIndex: 1, zoom: { scale: 4.5, x: 10,  y: 25  }, overlays: [], easing: 'ease-out' },
      { id: 'lc11', imageIndex: 1, zoom: { scale: 3.0, x: 25,  y: -20 }, overlays: [], easing: 'ease-in-out' },
      { id: 'lc12', imageIndex: 1, zoom: { scale: 1,   x: 0,   y: 0   }, overlays: [], easing: 'ease-out' },
    ],
    paragraphs: [
      { id: 'lcp1',  stateId: 'lc1',  text: 'The room smells of ink and beeswax. Maps cover every surface — pinned to walls, rolled in tubes, stacked in drawers that haven\'t closed properly in decades.' },
      { id: 'lcp2',  stateId: 'lc2',  text: 'His hands move with a steadiness that contradicts their age. The pen traces a coastline he has never visited but knows by heart — every inlet, every headland.' },
      { id: 'lcp3',  stateId: 'lc3',  text: 'The compass. Brass, German-made, older than its owner. He bought it at an estate sale forty years ago and has not used another instrument since.' },
      { id: 'lcp4',  stateId: 'lc4',  text: 'On the map beneath his hands, a continent takes shape. Not the clean vectors of a GPS trace, but something rougher, warmer — a landscape filtered through human attention.' },
      { id: 'lcp5',  stateId: 'lc5',  text: 'In the margins, he writes notes. Wind patterns. Tidal schedules. The name of a fisherman who corrected his rendering of a bay. The map becomes a journal.' },
      { id: 'lcp6',  stateId: 'lc6',  text: 'A candle flickers at the edge of the desk. He prefers it to electric light. Says the color temperature is closer to what the old navigators used. Perhaps he is right.' },
      { id: 'lcp7',  stateId: 'lc7',  text: 'He leans back. The full map is visible now. It is beautiful — not despite its imperfections but because of them. Every wobble in a line records a breath, a hesitation, a decision.' },
      { id: 'lcp8',  stateId: 'lc8',  text: 'Across the hall, his archive. Thousands of hand-drawn maps spanning forty years of work. Each one is a record of a place at a moment — a portrait, not a photograph.' },
      { id: 'lcp9',  stateId: 'lc9',  text: 'He pulls one from the shelf. A harbor in Norway, drawn in 1987. The fishing boats are gone now, replaced by oil platforms. But on this paper, they are still there.' },
      { id: 'lcp10', stateId: 'lc10', text: 'The detail is astonishing. Individual roof tiles. The shadow of a church spire at four in the afternoon. He drew it from a hilltop over three days, sleeping in his car.' },
      { id: 'lcp11', stateId: 'lc11', text: '"A satellite sees everything," he says. "But it understands nothing. A map drawn by hand is an act of interpretation. It tells you what matters."' },
      { id: 'lcp12', stateId: 'lc12', text: 'He returns the map to its place. There are fewer of them now, the people who do this. Soon there will be none. And the world will be perfectly mapped and entirely undescribed.' },
    ],
  },

  // ── Placeholder stories ──
  {
    id: '2',
    slug: 'vanishing-shores',
    title: 'Vanishing Shores',
    subtitle: 'How rising seas are reshaping coastlines and communities around the world',
    coverImage: story2Cover,
    author: 'Marcus Chen',
    date: 'February 2026',
    readTime: '9 min read',
    status: 'published',
    images: [story2Cover],
    states: [],
    paragraphs: [],
  },
  {
    id: '3',
    slug: 'above-the-clouds',
    title: 'Above the Clouds',
    subtitle: 'Life at extreme altitude — the communities thriving on the roof of the world',
    coverImage: story3Cover,
    author: 'Priya Sharma',
    date: 'January 2026',
    readTime: '15 min read',
    status: 'draft',
    images: [story3Cover],
    states: [],
    paragraphs: [],
  },
];
